Kalinga.PresentationLayer/Controllers/CampusMindsController.cs
using CustomExceptions;
using Kalinga.PresentationLayer.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Kalinga.PresentationLayer.Controllers
{
    public class CampusMindsController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        readonly ManagerModel managerModel = new ManagerModel();

        [HttpGet]
        public ActionResult GetCampusMinds()
        {
            var context = managerModel.DisplayDetailsOfLead();
            if (context != null)
            {
                ViewBag.data = context.ToList();
            }
            return View();
        }

        [HttpPost]
        public ActionResult GetCampusMinds(CampusMindsModel campusMindModel, MindtreeLeadsModel mindtreeLeadModel)
        {
            try
            {
                int rowAffected = managerModel.AddCampusMindsDetails(campusMindModel, mindtreeLeadModel);

                var context = managerModel.DisplayDetailsOfLead();
                if (context != null)
                {
                    ViewBag.data = context.ToList();
                }
                if (rowAffected > 0)
                {
                    ViewBag.message = "Data inserted successfully";
                }
                else
                {
                    ViewBag.message = "Data not inserted";
                }
            }
            catch (CustomSqlException ex)
            {
                ViewBag.message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View();
        }
        [HttpGet]

        public ActionResult DisplayCampusMinds()
        {
            List<CampusMindsModel> campusMindModels = new List<CampusMindsModel>();

            campusMindModels = managerModel.DisplayCampusMindDetails();
            return View(campusMindModels);
        }

        [HttpGet]
        public ActionResult UpdateMindDetails()
        {
            int id = 0;
            var context = managerModel.DisplayDetailsOfLead();

            if (context != null)
            {
                ViewBag.data = context.ToList();
            }
            return View(managerModel.DisplayCampusMindDetails().Find(Val => Val.MindId==id));
        }

        [HttpPost]
        public ActionResult UpdateMindDetails(CampusMindsModel campusMindModel, MindtreeLeadsModel mindtreeLeadModel)
        {
            try
            {
                int rowAffected = managerModel.UpdateMindDetail(campusMindModel, mindtreeLeadModel);

                ModelState.Clear();
                var context = managerModel.DisplayDetailsOfLead();
                if (context != null)
                {
                    ViewBag.data = context.ToList();
                }
                if (rowAffected > 0)
                {
                    ViewBag.message = "Updated Successfully";
                }
                else
                {
                    ViewBag.message = "Not updated..";
                }
            }
            catch (CustomSqlException ex)
            {
                ViewBag.message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View();
        }

        [HttpGet]
        public ActionResult GetLeadsDetails()
        {
            var context = managerModel.GetDetailsOfCategory();
            if (context != null)
            {
                ViewBag.data = context.ToList();
            }
            return View();
        }

        [HttpPost]
        public ActionResult GetLeadsDetails(MindtreeLeadsModel mindtreeLeadModel, CategoryModel categoryModel)
        {
            try
            {
                int rowAffected = managerModel.AddLeadDetails(mindtreeLeadModel, categoryModel);

                var context = managerModel.GetDetailsOfCategory();
                if (context != null)
                {
                    ViewBag.data = context.ToList();
                }
                if (rowAffected > 0)
                {
                    ViewBag.message = "Data inserted successfully";
                }
                else
                {
                    ViewBag.message = "Data not inserted";
                }
            }
            catch (CustomSqlException ex)
            {
                ViewBag.message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View();
        }

        [HttpGet]
        public ActionResult DisplayLeadDetails()
        {
            List<MindtreeLeadsModel> mindtreeLeadModels = new List<MindtreeLeadsModel>();

            mindtreeLeadModels = managerModel.DisplayDetailsOfLead();

            return View(mindtreeLeadModels);
        }

        [HttpGet]
        public ActionResult UpdateLeads()
        {
            int id = 0;
            var context = managerModel.GetDetailsOfCategory();
            if (context != null)
            {
                ViewBag.data = context.ToList();
            }
            return View(managerModel.DisplayDetailsOfLead().Find(Val => Val.LeadId == id));
        }

        [HttpPost]
        public ActionResult UpdateLeads(MindtreeLeadsModel mindtreeLeadModel, CategoryModel categoryModel)
        {
            try
            {
                int row = managerModel.UpdateLeadDetail(mindtreeLeadModel, categoryModel);
                ModelState.Clear();
                var context = managerModel.GetDetailsOfCategory();
                if (context != null)
                {
                    ViewBag.data = context.ToList();
                }
                if (row > 0)
                {
                    ViewBag.message = "Updated successfully";
                }
                else
                {
                    ViewBag.message = "not updated";
                }
                return View();
            }
            catch (CustomSqlException ex)
            {
                ViewBag.message = ex.Message;
            }
            catch (Exception ex)
            {
                ViewBag.message = ex.Message;
            }
            return View("Details");
        }
    }
}

Kalinga.PresentationLayer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Kalinga Management System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("GetLeadsDetails", "GetLeadsDetails", "CampusMinds")</li>
                    <li>@Html.ActionLink("GetCampusMinds", "GetCampusMinds", "CampusMinds")</li>
                    <li>@Html.ActionLink("DisplayLeadDetails", "DisplayLeadDetails", "CampusMinds")</li>
                    <li>@Html.ActionLink("DisplayCampusMinds", "DisplayCampusMinds", "CampusMinds")</li>
                    <li>@Html.ActionLink("UpdateMindDetails", "UpdateMindDetails", "CampusMinds")</li>
                    <li>@Html.ActionLink("UpdateLeads", "UpdateLeads", "CampusMinds")</li>
                    <li>@Styles.Render("~/Content/css")</li>
                    <li>
                        @Scripts.Render("~/bundles/modernizr");
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>